
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CheckIfServiceExistsParameters {
    /**
    * Label: Service Names, type: entry
    */
    String serviceNames

    static CheckIfServiceExistsParameters initParameters(StepParameters sp) {
        CheckIfServiceExistsParameters parameters = new CheckIfServiceExistsParameters()

        def serviceNames = sp.getRequiredParameter('serviceNames').value
        parameters.serviceNames = serviceNames

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: cfa191ff07de134b592328e21ad06c27 ===
