
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class CreateServiceParameters {
    /**
    * Label: Service Name, type: entry
    */
    String serviceName

    static CreateServiceParameters initParameters(StepParameters sp) {
        CreateServiceParameters parameters = new CreateServiceParameters()

        def serviceName = sp.getRequiredParameter('serviceName').value
        parameters.serviceName = serviceName

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 7cc69c72a1a195d6ff94766dac185d74 ===
