
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class DisableServiceParameters {
    /**
    * Label: Service Names, type: entry
    */
    String serviceNames
    /**
    * Label: Extra Arguments, type: textarea
    */
    String argString

    static DisableServiceParameters initParameters(StepParameters sp) {
        DisableServiceParameters parameters = new DisableServiceParameters()

        def serviceNames = sp.getRequiredParameter('serviceNames').value
        parameters.serviceNames = serviceNames
        def argString = sp.getParameter('argString').value
        parameters.argString = argString

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 2ed852345534ec195dfa55bc077620ec ===
