
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class EnableServiceParameters {
    /**
    * Label: Service Names, type: entry
    */
    String serviceNames
    /**
    * Label: Extra Arguments, type: textarea
    */
    String argString
    /**
    * Label: Start Type, type: select
    */
    String startType

    static EnableServiceParameters initParameters(StepParameters sp) {
        EnableServiceParameters parameters = new EnableServiceParameters()

        def serviceNames = sp.getRequiredParameter('serviceNames').value
        parameters.serviceNames = serviceNames
        def argString = sp.getParameter('argString').value
        parameters.argString = argString
        def startType = sp.getRequiredParameter('startType').value
        parameters.startType = startType

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 42100c6ad4df3acc76720e1c68ae5e2a ===
