
// DO NOT EDIT THIS BLOCK BELOW=== Parameters starts ===
// PLEASE DO NOT EDIT THIS FILE

import com.cloudbees.flowpdf.StepParameters

class StopServiceParameters {
    /**
    * Label: Service Names, type: entry
    */
    String serviceNames
    /**
    * Label: Wait for Stopped, type: checkbox
    */
    boolean waitFor
    /**
    * Label: Set Timeout, type: entry
    */
    String timeout

    static StopServiceParameters initParameters(StepParameters sp) {
        StopServiceParameters parameters = new StopServiceParameters()

        def serviceNames = sp.getRequiredParameter('serviceNames').value
        parameters.serviceNames = serviceNames
        def waitFor = sp.getParameter('waitFor').value == "true"
        parameters.waitFor = waitFor
        def timeout = sp.getParameter('timeout').value
        parameters.timeout = timeout

        return parameters
    }
}
// DO NOT EDIT THIS BLOCK ABOVE ^^^=== Parameters ends, checksum: 8faadca0a9494e61d2cc39e89a23ab9b ===
